### ISSUE TITLE
Change Popup Values

### ISSUE THREAD

**Issue by mateoclarke** [txappleseed/txappleseedmap#23]
![](http://dsh.re/62b81)

Change the popup from having pure numbers of students to the makeup of the percentage of the student body population

**Comment by mlsintx** [comment]
Mateo, do you mean, for example 6% of the student population was placed?  The problem with that is for the vert small populations, the percentage obfuscates the accuracy of the value, at least IMO.  That's why we decided that the actual numbers are preferable.

**Comment by mateoclarke** [comment]
Not sure 💯. But yes, that sounds right. In the example above of 188 placements out of 2455 students, we could call that a 7.66% placement rate and add it to the pop over.

I'm just parroting here what @codecofee19 said on the #texasappleseed Slack channel about what he thought needed to get updated.

We should loop in Morgan and maybe also @mscarey on whether they share your opinion @mlsintx. Maybe it is not a necessary change/update.

**Comment by codecofee19** [comment]
@mlsintx @mateoclarke  Sorry it's been a while and I may be a little fuzzy on what Yamanda actually specified around the time. I believe though the main concern with pure numbers was that users wouldn't understand that certain ethnicities and groups received these punishments more frequently than others. And people looking at other districts may not understand when looking at certain districts that relative to that district size and the total alternative placements that these students are targeted more frequently. If for example, in a small district of 500 students, 15 native american students are in alternative placement. A user might glance over that district and believe that it doesn't seem too bad. However, if it turns out those students comprised of 75% of the total alternative placements in the district, then it shows that it heavily targets and harms a certain demographic of the student population.

**Comment by mateoclarke** [comment]
From @mscarey:

"[20] percent of [District Name]'s [5000] students are [group name].  
[50] percent of the district's [500] [disciplinary alternative education]  punishments went to students who are [group name]."

**Comment by mateoclarke** [comment]
For now, popups look like this:
![](http://dsh.re/2a7f4)

This could be improved with better formatting, but it does the job for now. Further suggestions or improvements are welcome, but let's do that in a new issue if necessary.
