### ISSUE TITLE
More maps?

### ISSUE THREAD

**Issue by mateoclarke** [txappleseed/txappleseedmap#24]
- [x] Alternative School Placements 
- [x] in-school suspensions
- [x] out-of-school suspensions
- [x] expulsions

> There are apparently three more maps that still need to be created, but I'm not sure if we ever figured out what they were
> - @codecofee19 
> 
> The three other maps that would have been created would have covered in-school suspensions, out-of-school suspensions, and expulsions, for the same categories as the existing map. Those categories are all in the CSV that was used to create the map. (It would have been best to show everything in one map, but nobody could figure out how.)
> - @mscarey

**Comment by mlsintx** [comment]
Yes, the other maps should be easy to build once this 'template' is finalized.  Having this much data (for all punishments) would not be good.  We could make a fifth map with the total values just for comparison of the punishment types.  Having the populations broken out needs to be limited to one type.  For the sake of getting this template finished, I can restyle the popups and I personally think they need to show popups as a click event rather than the hover.  This will have to happen for mobile devices anyway.   The other pressing need is some changes to make the maps viewable on mobile.  Maybe jquery?  That is something I'm not very familiar with.  I have learned some possible tools lately, but I don't know how much time I have to work on that.  Do you know of anyone?

**Comment by mateoclarke** [comment]
Cool, we have a seperate Issue open for mobile. #25 

I personally don't think click vs hover is a big deal. I think hover events get executed with click behavior in modern mobile browsers without changing code. _Could be wrong about this assumption_

**Comment by mateoclarke** [comment]
Where does the data live for the other maps? @MCraven2800?

**Comment by mlsintx** [comment]
@mateoclarke It's served out of texasappleseed's Carto account. That was originally because the maps were going to be served from there, but that is not how we are doing it now. The source, though is the csv that Matt put together.  Would it be better to move the data over to the open Austin Carto account while the maps are being developed?

**Comment by mateoclarke** [comment]
### Datasets
1. Alternative School Placement 🍎
2. In School Suspensions 🍎
3. Out of School Suspensions 🌟 🍎
4. Expulsions 🍎
5. Student Arrests 🌟 🍏
6. Class "C" Tickets 🌟 🍏

🌟 = priority from Morgan
🍎 = data from TEA (Disciplinary Data)
🍏 = data from Yamanda's research (Ticketing and Arrest Data)
