### ISSUE TITLE
duplicate district geometry

### ISSUE THREAD

**Issue by mscarey** [txappleseed/txappleseedmap#67]
It looks like we have multiple copies of the school district shapes in the geojson directory: one copy for each type of disciplinary action. Does that mean if someone visits the map and selects each of the menu options, the identical district shapes will have to be loaded to their browser multiple times? Can we make it so the district shapes only load once, even if the other data reloads when a button is pushed?

**Comment by mlsintx** [comment]
Mateo and I were talking about that today.  Yes, we have been loading a geojson file for each punishment instead of having to make the load happen a bit more quickly.  I have been looking at changes to load the geometries onload, and then load the attributes onclick to make the initial load smaller and and improve performance.  In other words, we are working on it :)

**Comment by mscarey** [comment]
@rebfrank solved this!
